### ISSUE TITLE
Author Feedback Table 

### ISSUE THREAD

**Issue by Micah-Gafford** [lburgess07/expertiza#4]
For “Author feedback report” table, change the header name “Review response rejoined” to “Review responded to” and “Last rejoined at” to “Last responded at”. Then, sort “Rejoinder” and “Review responded to” as string (alphabetically), sort “# author feedbacks done” by the first number then the second number (same as “Review done” in the “View review report” table) and sort “Last responded at” as date.

**Comment by johnbumgardner** [comment]
Functionality finished. Bug fixed. Need to fix drag and drop.
